name: Sync Related Tools Section

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch Gist content
      run: |
        GIST_CONTENT=$(curl -s https://gist.githubusercontent.com/m-c-frank/5b7a099c0998e3030888125370b26195/raw/)
        # Use some method (e.g., a script) to replace the "Related Tools" section in README.md with $GIST_CONTENT

    - name: Commit and push if there's a change
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Updated Related Tools section" && git push)
